apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: slimserve-data
  name: slimserve-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
