apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-ssl-secrets-slimserve
  namespace: traefik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: slimserve
  to:
    - group: ""
      kind: Secret
      name: wildcard-savew.dev-tls
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-ssl-secrets-mc
  namespace: traefik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: game-compose
  to:
    - group: ""
      kind: Secret
      name: wildcard-savew.dev-tls
