apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: copilot-api-data
  name: copilot-api-data
  namespace: litellm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
