apiVersion: v1
kind: Service
metadata:
  labels:
    service: litellm
  name: litellm
  namespace: litellm
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    service: litellm
