apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm
  namespace: litellm
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: litellm
      owner: litellm
      secret:
        name: production
  storage:
    size: 5Gi
