apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sun
subjects:
  - kind: ServiceAccount
    name: sun
    namespace: sun
roleRef:
  kind: ClusterRole
  name: sun
  apiGroup: rbac.authorization.k8s.io
