apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sun

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml

images:
  - name: ghcr.io/bouquet2/sun
    newTag: 0.1.5

secretGenerator:
  - name: sun-secrets
    envs:
      - .env
    options:
      disableNameSuffixHash: true
