apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - umami-deployment.yaml
  - umami-service.yaml
  - ingressroute.yaml
namespace: umami
secretGenerator:
  - name: production
    namespace: umami
    envs:
      - .env
    options:
      disableNameSuffixHash: true
images:
  - name: ghcr.io/umami-software/umami
    newTag: postgresql-v2.18.1
