apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: umami-db
  namespace: umami
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: umami
      owner: umami
      secret:
        name: production
  storage:
    size: 1Gi
