resources:
  - namespace.yml
  - subnet-router.yml
helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.86.2
    releaseName: tailscale-operator
    valuesFile: values.yaml
    namespace: tailscale
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: operator-oauth
    namespace: tailscale
    envs:
      - ./.operator-secret.env
  - name: tailscale-auth
    namespace: tailscale
    envs:
      - ./.tailscale-secret.env
