apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moniquet
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["longhorn.io"]
    resources: ["volumes", "replicas", "engines", "nodes", "backups"]
    verbs: ["get", "list", "watch"]

