apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moniquet
subjects:
  - kind: ServiceAccount
    name: moniquet
    namespace: moniquet
roleRef:
  kind: ClusterRole
  name: moniquet
  apiGroup: rbac.authorization.k8s.io
