apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: moniquet
spec:
  selector:
    matchLabels:
      app: moniquet
  template:
    metadata:
      labels:
        app: moniquet
    spec:
      serviceAccountName: moniquet
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: moniquet
          image: ghcr.io/kreatoo/moniquet
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: moniquet-secrets
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: moniquet-config
