apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moniquet

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml

images:
  - name: ghcr.io/kreatoo/moniquet
    newTag: 0.0.13

secretGenerator:
  - name: moniquet-secrets
    envs:
      - .env
    options:
      disableNameSuffixHash: true
