apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: copilot-api
  namespace: argocd
spec:
  destination:
    namespace: open-webui-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: copilot-api
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  destination:
    namespace: open-webui-k8s
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: open-webui
    helm:
      parameters:
        - name: postgresql.secret.autoCreate
          value: kustomize
      values: |-
        resources:
          limits:
            cpu: 400m
            memory: 2048Mi
    repoURL: https://helm.mtaha.dev
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
