apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: open-webui-data
  name: open-webui-data
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
