apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-savew.dev
  namespace: traefik
spec:
  secretName: wildcard-savew.dev-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "adguard-home"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "adguard-home"
  dnsNames:
    - "savew.dev"
    - "*.savew.dev"
  issuerRef:
    name: mainissuer
    kind: ClusterIssuer
