resources:
  - namespace.yml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    version: v1.18.2
    namespace: traefik
    valuesInline:
      installCRDs: true

secretGenerator:
  - name: cloudflare-api-token-secret
    namespace: traefik
    envs:
      - ./.env
