name: Deploy & Upgrade K0s

on:
  push:
    paths:
      - 'vars.yaml'
  workflow_call:
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k0s-upgrade
          version: latest
          hostname: hivetool-k0s

      - name: Install k0sctl
        run: |
          sudo wget https://github.com/k0sproject/k0sctl/releases/latest/download/k0sctl-linux-amd64 -O /usr/local/bin/k0sctl
          sudo chmod +x /usr/local/bin/k0sctl

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Extract k0s version from vars.yaml
        id: extract_version
        run: |
          version=$(yq e '.k0sVersion' vars.yaml)
          echo "k0s_version=$version" >> "$GITHUB_OUTPUT"

      - name: Debug version
        env:
          K0S_VERSION: ${{ steps.extract_version.outputs.k0s_version }}
        run: |
          echo "Using k0s version: $K0S_VERSION"

      - name: Deploy & Upgrade K0s
        env:
          CONTROL_PLANE_IP: ${{ secrets.CONTROL_PLANE }}
          WORKER_1_IP: ${{ secrets.WORKER_1 }}
          WORKER_2_IP: ${{ secrets.WORKER_2 }}
          K0S_VERSION: ${{ steps.extract_version.outputs.k0s_version }}
        run: |
          k0sctl apply --config ./templates/k0sctl-workflow.yaml
